### ISSUE TITLE
是否可以指定curl的版本？比如curl-7.80.0版本

### ISSUE THREAD

**Issue by JIAQIA** [ibaoger/libcurl-android#10]
在某些场景下，可能需要编译指定版本的curl或openssl，比如在使用cpr时，需要指定7.80版本的curl，高版本的curl库cpr还暂时不支持。在交叉编译Android cpr时，需要做这方面的尝试。

**Comment by ibaoger** [comment]
初始化项目命令如下
```
git clone https://github.com/shishuo365/libcurl-android.git
cd libcurl-android
git submodule init && git submodule update
```

然后，使用 git命令或 git界面工具，手动把 openssl curl zlib 源码重置到你想要的版本，然后编译即可。

**Comment by JIAQIA** [comment]
@ibaoger 感谢，提完问题以后反应过来了。已经编译好了，感谢。checkout一下版本即可。有时候脑子短路。
