### ISSUE TITLE
编译 curl 的时候报错。

### ISSUE THREAD

**Issue by objectZhang** [ibaoger/libcurl-android#8]
我按照要求已经成功编译出了 openssl ，但是在编译 curl 的时候报错。

checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking dependency style of /Users/liang.zhang/Downloads/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc... gcc3
checking curl version... 7.74.0-DEV
checking build system type... i386-apple-darwin19.2.0
checking host system type... Invalid configuration `arm-linux-androideabi': system `androideabi' not recognized
configure: error: /bin/sh ./config.sub arm-linux-androideabi failed
Error building curl library

编译平台 Mac, NDK 版本是 13B

**Comment by shishuo365** [comment]
看一下NDK变量配置，
echo $NDK_ROOT
然后，查看编译脚本是否有改动，先使用下载好没有修改的脚本跑一遍
